"""empty message

Revision ID: 13746bb16d7b
Revises: 7e604ea23e7f
Create Date: 2020-02-13 21:47:32.509357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13746bb16d7b'
down_revision = '7e604ea23e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exttargetaccess', sa.Column('proxy_pid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exttargetaccess_proxy_pid'), 'exttargetaccess', ['proxy_pid'], unique=False)
    op.create_foreign_key(None, 'target_log', 'target', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target_log', type_='foreignkey')
    op.drop_index(op.f('ix_exttargetaccess_proxy_pid'), table_name='exttargetaccess')
    op.drop_column('exttargetaccess', 'proxy_pid')
    # ### end Alembic commands ###
