"""empty message

Revision ID: 40608ac987ff
Revises: 337cacabaf14
Create Date: 2018-10-10 21:21:33.731103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40608ac987ff'
down_revision = '337cacabaf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sshkeyhash', sa.String(length=5000), nullable=True))
    op.create_index(op.f('ix_user_sshkeyhash'), 'user', ['sshkeyhash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sshkeyhash'), table_name='user')
    op.drop_column('user', 'sshkeyhash')
    # ### end Alembic commands ###
