"""empty message

Revision ID: 7e10f8660fa5
Revises: a468530a43fa
Create Date: 2018-05-11 21:59:01.031948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e10f8660fa5'
down_revision = 'a468530a43fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connectiondate', sa.String(length=20), nullable=True),
    sa.Column('password', sa.LargeBinary(length=500), nullable=True),
    sa.Column('salt', sa.LargeBinary(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passentry_connectiondate'), 'passentry', ['connectiondate'], unique=False)
    op.create_index(op.f('ix_passentry_password'), 'passentry', ['password'], unique=False)
    op.create_index(op.f('ix_passentry_salt'), 'passentry', ['salt'], unique=False)
    op.create_table('target_pass',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('logentry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logentry_id'], ['passentry.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('target_id', 'logentry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_pass')
    op.drop_index(op.f('ix_passentry_salt'), table_name='passentry')
    op.drop_index(op.f('ix_passentry_password'), table_name='passentry')
    op.drop_index(op.f('ix_passentry_connectiondate'), table_name='passentry')
    op.drop_table('passentry')
    # ### end Alembic commands ###
