"""empty message

Revision ID: 9757d86a4c2c
Revises: 40608ac987ff
Create Date: 2019-07-16 23:32:49.931418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9757d86a4c2c'
down_revision = '40608ac987ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logfilesize', sa.String(length=30), nullable=True))
    op.drop_index('ix_user_sshkeyhash', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_sshkeyhash', 'user', ['sshkeyhash'], unique=False)
    op.drop_column('user', 'logfilesize')
    # ### end Alembic commands ###
