"""empty message

Revision ID: a468530a43fa
Revises: 
Create Date: 2018-05-11 21:27:18.328272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a468530a43fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logentry', 'connectioncmd',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('logentry', 'connectiondate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_logentry_connectioncmd'), 'logentry', ['connectioncmd'], unique=False)
    op.create_index(op.f('ix_logentry_connectiondate'), 'logentry', ['connectiondate'], unique=False)
    op.create_index(op.f('ix_logentry_pid'), 'logentry', ['pid'], unique=False)
    op.create_foreign_key(None, 'target_log', 'logentry', ['logentry_id'], ['id'])
    op.create_foreign_key(None, 'target_log', 'target', ['target_id'], ['id'])
    op.create_foreign_key(None, 'user_log', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_log', 'logentry', ['logentry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_log', type_='foreignkey')
    op.drop_constraint(None, 'user_log', type_='foreignkey')
    op.drop_constraint(None, 'target_log', type_='foreignkey')
    op.drop_constraint(None, 'target_log', type_='foreignkey')
    op.drop_index(op.f('ix_logentry_pid'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_connectiondate'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_connectioncmd'), table_name='logentry')
    op.alter_column('logentry', 'connectiondate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('logentry', 'connectioncmd',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
