"""empty message

Revision ID: f992559bf040
Revises: 
Create Date: 2018-02-15 21:52:01.057731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f992559bf040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('connectiondate', sa.String(length=20), nullable=True),
    sa.Column('connectioncmd', sa.String(length=200), nullable=True),
    sa.Column('logfilepath', sa.String(length=200), nullable=True),
    sa.Column('logfilename', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logentry_connectioncmd'), 'logentry', ['connectioncmd'], unique=False)
    op.create_index(op.f('ix_logentry_connectiondate'), 'logentry', ['connectiondate'], unique=False)
    op.create_index(op.f('ix_logentry_pid'), 'logentry', ['pid'], unique=False)
    op.create_table('target_log',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('logentry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logentry_id'], ['logentry.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('target_id', 'logentry_id')
    )
    op.create_table('user_log',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logentry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logentry_id'], ['logentry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'logentry_id')
    )
    op.drop_table('tgroup_tgroup')
    op.drop_table('migrate_version')
    op.add_column('user', sa.Column('superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'superadmin')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_table('tgroup_tgroup',
    sa.Column('targetgroup_id', sa.INTEGER(), nullable=False),
    sa.Column('containertargetgroup_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['containertargetgroup_id'], ['targetgroup.id'], ),
    sa.ForeignKeyConstraint(['targetgroup_id'], ['targetgroup.id'], ),
    sa.PrimaryKeyConstraint('targetgroup_id', 'containertargetgroup_id')
    )
    op.drop_table('user_log')
    op.drop_table('target_log')
    op.drop_index(op.f('ix_logentry_pid'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_connectiondate'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_connectioncmd'), table_name='logentry')
    op.drop_table('logentry')
    # ### end Alembic commands ###
