#!/usr/bin/env python
# -*-coding:Utf-8 -*-

# Compatibility 2.7-3.4
from __future__ import absolute_import
from __future__ import unicode_literals

import os,ssl
from config import SQLALCHEMY_DATABASE_DIR
from config import SSL_CERTIFICAT
from config import SSL_KEY
from config import HOST
from config import SSL


"""Server side using flask"""
from app import app


if not os.path.exists(SQLALCHEMY_DATABASE_DIR):
    print("ERROR: Database connection failed")
else:
    if SSL == False:
        if HOST is not "127.0.0.1":
            print("WARNING: Run unsecure mode (no SSL), force use of" + \
                  " 127.0.0.1.")
        app.run()
    else:
        SSL_CONTEXT  = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
        SSL_CONTEXT.load_cert_chain(SSL_CERTIFICAT, SSL_KEY)
        app.run(host = HOST, ssl_context = SSL_CONTEXT)
