#!/usr/bin/env python
# -*-coding:Utf-8 -*-

# Compatibility 2.7-3.4
from __future__ import absolute_import
from __future__ import unicode_literals

import os
from config import SQLALCHEMY_DATABASE_DIR
from config import SSL_CONTEXT
from config import HOST


"""Server side using flask"""
from app import app


if not os.path.exists(SQLALCHEMY_DATABASE_DIR):
    print("ERROR: Database connection failed")
else:
    if SSL_CONTEXT == False:
        app.run()
    else:
        app.run(host = HOST, ssl_context = SSL_CONTEXT)
