name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: ls -la /usr/local/lib/node_modules
      - run: chown $(id -u):$(id -g) /usr/local/lib/node_modules
      - run: npm install -g bats
      - run: bats -v
